### ISSUE TITLE
GitHub에서 Source 다운받아서 새 PC에서 실행하는데, 왜 안되지?

### ISSUE THREAD

**Issue by Derek-TheFox** [Derek-TheFox/ch3#4]
C:\ch3>python manage.py runserver
Traceback (most recent call last):
  File "C:\ch3\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ch3\manage.py", line 22, in <module>
    main()
  File "C:\ch3\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by Derek-TheFox** [comment]
virtual environment 설정이 안되서 그런거 같은데... 사실 이 개념 제대로 이해 안하고 넘어갔는데...
Wiki에 virtual environment 설정하는 방법 공부해서 등록해야겠다!!
